<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="product.xsl"?>
<!DOCTYPE product [
<!ELEMENT product (productdata)>
<!ELEMENT productdata (id, name, detail, price, stock)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT detail (#PCDATA)>
<!ELEMENT price (#PCDATA)> 
<!ELEMENT stock (#PCDATA)>
]>

<product>
    <productdata>
        <id>1111</id>
        <name>Blue Archive Arona figure</name>
        <detail>ฟิกเกอร์ arona จากBlue archive ขนาด 22cm</detail>
        <price>498</price>
        <stock>75</stock>
    </productdata>
    <productdata>
        <id>2222</id>
        <name>Tokisaki Kurumi figure</name> 
        <detail>Tokisaki Kurumiฟิกเกอร์ Light Novel สําหรับตกแต่งบ้าน</detail> 
        <price>391</price>
        <stock>558</stock>
    </productdata>
    <productdata>
        <id>3333</id>
        <name>Evangelion UnitFigure</name> 
        <detail>Evangelion UnitFigure Neon Genesis Evangelion ขนาด 17 ซม</detail> 
        <price>395</price>
        <stock>4150</stock>
    </productdata>
    <productdata>
        <id>4444</id>
        <name>Hitori Goto</name>
        <detail>Hitori Goto โมเดลฟิกเกอร์ ขนาด 8 ซม. ของเล่น ของขวัญ สําหรับเก็บสะสม</detail> 
        <price>210</price>
        <stock>900</stock>
    </productdata>
    <productdata>
        <id>5555</id>
        <name>Sword Art Online Asuna figure</name> 
        <detail>Asuna figure178 ขนาด 14 ซม. สําหรับเก็บสะสม</detail> 
        <price>208</price>
        <stock>511</stock>
    </productdata>
</product>