<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="sales.xsl"?>
<!DOCTYPE sale [
<!ELEMENT sales (sale*)>
<!ELEMENT sale (saleid, saledate, productname, price, total)>
<!ELEMENT saleid (#PCDATA)>
<!ELEMENT saledate (#PCDATA)>
<!ELEMENT productname (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT total (#PCDATA)>
]>

<sales>
    <sale>
        <saleid>A1234</saleid>
        <saledate>10/02/2567</saledate>
        <productname>Blue Archive Arona figure</productname>
        <price>498</price>
        <total>498</total>
    </sale>
    <sale>
        <saleid>B1234</saleid>
        <saledate>11/02/2567</saledate>
        <productname>Tokisaki Kurumi figure</productname>
        <price>213</price>
        <total>213</total>
    </sale>
    <sale>
        <saleid>C1234</saleid>
        <saledate>12/02/2567</saledate>
        <productname>Evangelion UnitFigure</productname>
        <price>210</price>
        <total>210</total>
    </sale>
    <sale>
        <saleid>D1234</saleid>
        <saledate>13/02/2567</saledate>
        <productname>Hitori Goto</productname>
        <price>208</price>
        <total>208</total>
    </sale>
    <sale>
        <saleid>E1234</saleid>
        <saledate>14/02/2567</saledate>
        <productname>Sword Art Online Asuna figure</productname>
        <price>391</price>
        <total>511</total>
    </sale>
</sales>
